name: Docker Compose Deploy

on:
  push:
    branches:
      - backend # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 빌드와 배포 스크립트 실행 (서버 배포)
      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # 서버에 SSH로 접속
          ssh $SERVER_USER@$SERVER_IP << EOF
            # 작업 디렉토리로 이동
            cd ~/term_backend

            # 최신 코드 가져오기+적용
            bash reload.sh

            # 작업폴더로 이동
            cd ~/term_backend/TermMaker/backend/

            # docker-compose 서비스 갱신
            docker-compose down
            docker-compose pull
            sudo docker-compose up -d --build
          EOF
